CREATE TABLE patient_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,

    CONSTRAINT uk_patient_profiles_user_id UNIQUE (user_id),
    CONSTRAINT fk_patient_profiles_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE
);